apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    {{- include "billiard.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    {{- include "billiard.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
