apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "billiard.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.backend.jwtSecret | default "CHANGE-ME" | quote }}
  ADMIN_PASSWORD: {{ .Values.backend.adminPassword | default "admin123" | quote }}
  FRONTEND_KEY: {{ .Values.backend.frontendKey | default "CHANGE-ME" | quote }}
